const express = require("express");
const router = express.Router();
const controller = require("../controllers/user.controller");
const authMiddlware = require("../middleware/auth.middleware");
router.post("/register", controller.register);
router.post("/login", controller.login);
router.post("/password/forgot", controller.forgotPassword);
router.post("/password/otp", controller.otpPassword);
router.post("/password/resetpassword", controller.resetPassword);
router.get("/detail", authMiddlware.requireAuth, controller.detail);
router.get("/list", authMiddlware.requireAuth, controller.list);
module.exports = router;
